app:
  build: .
  links:
    - db:db
  ports:
    - "3000:3000"
  environment:
    - GOOGLE_CLIENT_ID="933623108791-imtedbq5d1vgfhotj15gq6493jl22j4m.apps.googleusercontent.com"
    - GOOGLE_CLIENT_SECRET="HjKW82HOb1jT-XyWgPFc9jW8"
    - GOOGLE_CALLBACK_URL="http://127.0.0.1:3000/v2/auth/google/callback"
    - DATABASE_URL=postgres://postgres@db/postgres?sslmode=disable
    - PORT=3000
    - MIGRATIONS=true
  volumes:
    - .:/go/src/bitbucket.org/dukex/uhura-api

db:
  image: postgres
  volumes:
    - /var/lib/postgresql/data:/var/lib/postgresql/data
